### ISSUE TITLE
flow.md改进意见

### ISSUE THREAD

**Issue by xuewang** [WoSai/shouqianba-doc#3]
- 应说明请求和反馈都是`UTF-8`编码；这两天遇到有开发碰到签名错误，是因为签名算法用的utf-8，而请求时不是。
- “采用传输层签名机制”这句话有问题；HTTP首部签名应该是应用层而非传输层。
- “将HTTP请求body部分字节流视为被签名的内容”；应说明是utf-8字节流，因为遇到了由于body中有中文而未使用utf-8字节流做签名而导致的签名错误。

**Comment by jasonshao** [comment]
@xuewang 
问题1，3属于优化，可以直接修正中文版。
问题2应该是个错误，可以直接修正中文版。

**Comment by xuewang** [comment]
已修正
